#!/bin/bash
name="1"
age="1"
while [[ -n $name && $age -ne 0 ]]
do
echo "enter your name:"
read name
if [[ -z $name ]]
then
echo "bye"
break
fi
echo "enter your age:"
read age
if [[ $age -eq 0 ]]
then
echo "bye"
break
elif [[ $age -le 16 && $age -gt 0 ]]
then
echo "$name, your group is child"
elif [[ $age -ge 17 && $age -le 25 ]]
then
echo "$name, your group is youth"
elif [[ $age -gt 25 ]]
then
echo "$name, your group is adult"
fi
done
